# Configurazione per ambiente di SVILUPPO
# Per usare: gradlew bootRun --args='--spring.profiles.active=dev'
# Oppure: set SPRING_PROFILES_ACTIVE=dev && gradlew bootRun

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: postgres
    password: Qwertyui123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

s3:
  endpoint: s3.eu-central-2.idrivee2.com
  region: eu-central-2
  access-key: U8luoJLRrBurwwOWeaNO
  secret-key: V4msqaMV7sR8UrZ7zefvftNQChnk9LSx5vHVXdDi
  bucket:
    media: ${S3_MEDIA_BUCKET}-dev
    avatar: ${S3_AVATAR_BUCKET}-dev

media:
  upload:
    base-url: http://localhost:8080/api/media

avatar:
  upload:
    base-url: http://localhost:8080/api/users/avatars

jwt:
  secret: z7bmKAzWOtOjelu0OTsmPoF9zO+S4Lj/CulHkSppQbmdgfo5zmAa6LYLbYJMCdU4EJbkM67CAvykKuPTP7EpHQ==
  expiration: 86400000  # 24 ore

server:
  port: 8080

active-profile: ${SPRING_PROFILES_ACTIVE:dev}