spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cms_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Qwertyui123!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

s3:
  endpoint: ${S3_ENDPOINT:s3.eu-central-2.idrivee2.com}
  region: ${S3_REGION:eu-central-2}
  access-key: ${S3_ACCESS_KEY:U8luoJLRrBurwwOWeaNO}
  secret-key: ${S3_SECRET_KEY:V4msqaMV7sR8UrZ7zefvftNQChnk9LSx5vHVXdDi}
  bucket:
    media: ${S3_MEDIA_BUCKET:cms-media}
    avatar: ${S3_AVATAR_BUCKET:cms-avatars}

media:
  upload:
    base-url: ${MEDIA_BASE_URL:http://localhost:8080/api/media}

avatar:
  upload:
    base-url: ${AVATAR_BASE_URL:http://localhost:8080/api/users/avatars}

jwt:
  secret: ${JWT_SECRET:z7bmKAzWOtOjelu0OTsmPoF9zO+S4Lj/CulHkSppQbmdgfo5zmAa6LYLbYJMCdU4EJbkM67CAvykKuPTP7EpHQ==}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${SERVER_PORT:8080}

active-profile: ${SPRING_PROFILES_ACTIVE}