spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cms_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Qwertyui123!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

media:
  upload:
    directory: ${MEDIA_UPLOAD_DIR:./uploads}
    base-url: ${MEDIA_BASE_URL:http://localhost:8080/api/media}

avatar:
  upload:
    directory: ${AVATAR_UPLOAD_DIR:./avatars}
    base-url: ${AVATAR_BASE_URL:http://localhost:8080/api/users/avatars}

jwt:
  secret: ${JWT_SECRET:z7bmKAzWOtOjelu0OTsmPoF9zO+S4Lj/CulHkSppQbmdgfo5zmAa6LYLbYJMCdU4EJbkM67CAvykKuPTP7EpHQ==}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${SERVER_PORT:8080}

profile: ${SPRING_PROFILES_ACTIVE:dev}